# Generated by Django 2.0.1 on 2018-02-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myscrumy', '0002_auto_20180211_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolez',
            name='role_value',
            field=models.IntegerField(default=700),
        ),
    ]
