# Generated by Django 2.0.1 on 2018-02-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myscrumy', '0005_auto_20180211_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='status_id',
            field=models.ForeignKey(default=700, on_delete=django.db.models.deletion.PROTECT, to='myscrumy.Status'),
        ),
    ]
