# Generated by Django 2.0.1 on 2018-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myscrumy', '0008_auto_20180212_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumyuser',
            name='role_value',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='created_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='moved_by',
            field=models.CharField(default='not been moved', max_length=50),
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='movement_track',
            field=models.CharField(default='not been moved', max_length=100),
        ),
        migrations.DeleteModel(
            name='Rolez',
        ),
    ]
