# Generated by Django 2.0.1 on 2018-03-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myscrumy', '0009_auto_20180324_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='movement_track',
            field=models.IntegerField(default=1234),
        ),
    ]
