# Generated by Django 2.0.1 on 2018-03-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myscrumy', '0010_auto_20180325_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='status_id',
        ),
    ]
