# Generated by Django 2.0.1 on 2018-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myscrumy', '0012_remove_scrumyuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumygoals',
            name='owner',
            field=models.CharField(default='unassigned', max_length=50),
        ),
    ]
